### ISSUE TITLE
Updates once a week 

### ISSUE THREAD

**Issue by dimdimich** [tmhub/core#3]
in you TM Core extension the longest time to check for "News to show in notification bar" is every 24 hours. That is a little bit too often, could you please add more options, like once a week.

**Comment by vovayatsyuk** [comment]
Module uses `adminhtml/system_config_source_notification_frequency` model. It does not have another time option.

But do we post a news every day? I mean, if you increase this time to once a week, you will not notice any difference.

You will just receive a notification not in publish day, but a few(up to 7) days later after the article will be published.

**Comment by dimdimich** [comment]
Ok let's ignore that.
